package com.gbr.network

import android.content.Context
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions

object GoogleSignInProvider {
    fun getClient(context: Context): GoogleSignInClient {
        // Get the web client ID from string resources
        // This is automatically generated by Firebase from google-services.json
        val webClientId = try {
            val resourceId = context.resources.getIdentifier(
                "default_web_client_id",
                "string",
                context.packageName
            )
            if (resourceId != 0) {
                context.getString(resourceId)
            } else {
                null
            }
        } catch (e: Exception) {
            null
        }

        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .apply {
                if (webClientId != null) {
                    requestIdToken(webClientId)
                }
            }
            .requestEmail()
            .build()

        return GoogleSignIn.getClient(context, gso)
    }
}
